Revert change in mongoc-cache.c
Despite the #include, the linker does not like this:
tests/test-mongoc-cache.c.o: In function `ping':
src/libmongoc/tests/test-mongoc-cache.c:45: undefined reference to `test_framework_client_new'